### ISSUE TITLE
Yes, I'm aware the website is down

### ISSUE THREAD

**Issue by 4383** [sourceoptics/src_optics#2]
When I try to browse http://sourceoptics.io/ I obtain a "403 forbidden" access page.

![broken](https://user-images.githubusercontent.com/1541489/58018595-8a7bd380-7b03-11e9-94ae-e495ba77fb5e.png)

**Comment by mpdehaan** [comment]
Yep, I'm aware of it and have taken it up with the hosting provider.

There's really not any new content to see other than the blog post's screenshots, so you aren't missing anything, check out the README.md and INSTALL.md for info.

**Comment by 4383** [comment]
ok so I'll close it
